### PR TITLE
Fix "Cannot read property 'initial' of undefined".

### PR DESCRIPTION
**Pull request by stephenzhao**
when the chunks is null,  it will throw the error.

### CODE REVIEW

**Comment by sokra** [comment]
There seem to be some error somewhere. `chunk.chunks` should not have null elements. I'll close this PR because this doesn't fix the origin bug, but I'm interested to find the origin bug.

**Comment by scottyeck** [comment]
Was this ever addressed? Would love to try and fix.

**Comment by evilebottnawi** [comment]
@scottdj92  can your create minimal reproducible test repo?

**Comment by r1b** [comment]
my repo has this issue https://github.com/computer-lab/salon94design.com/releases/tag/chunks-bug

**Comment by r1b** [comment]
Introduced in https://github.com/computer-lab/salon94design.com/commit/52b08c5123d81532d0a7be47805ed7598710d5c0

**Comment by r1b** [comment]
This commit introduces the issue: https://github.com/computer-lab/salon94design.com/commit/d7ca2cc9a7b60fb9d0ce56044302284add368d90

**Comment by revolunet** [comment]
added a fix for webpack 1 too.

what about warning the user that its chunk is empty or invalid ?

**Pull request closed without merging**
