### PR TITLE
Fix proposal for issues #82 and #115. Adding extra tests for chunks existence in lists solved the problem.

### PR DESCRIPTION
**Pull request by RabidFX**
I am not 100 % sure that it cannot have drawbacks in some edge cases.

### CODE REVIEW

**Comment by RabidFX** [comment]
I'll work on a test case.

**Comment by brresnic** [comment]
@RabidFX, could you elaborate on why your fix fails some test cases?

**Comment by RabidFX** [comment]
@brresnic Actually, it passes all of them. The two "failed checks" are not test cases, it's compliance to codecov metrics:
- codecov/patch: Only 67.00% of the lines I modified are verified by a test case (target 90.00%)
- codecov/project: Overall code coverage of the project is lower after my commits.

I'm currently writing a new test case that should address both points. (I'll try to commit it tonight.)

**Comment by RabidFX** [comment]
The test case is proving to be much more challenging than I thought. It takes very specific conditions to trigger the "ghost chunk" problem, therefore covering the new code lines with a test.

The only test case I have so far is a whole project, very far from the low-footprint test cases, and with several new dependencies.

**Comment by RabidFX** [comment]
The test case is done. I have removed the safeguard on addParent() since it seems I was not able to make the chunk search fail in that loop. Perhaps it's completely failproof, perhaps it's just a question of finding an "edgier" case. Hence removing the fix, to ensure code coverage.

In any case, I left only the safeguard on the addChunk() method, and the fix still works. 

@sokra, feel free to pull this in the main repo. I have no plans on working on this any further unless someone asks :smile:  
I don't know what codecov has been drinking, but with 100% patch coverage, I fail to see how project coverage would diminish, so I'm quite sure you can pull without fear. :smile:

**Pull request closed without merging**
