### PR TITLE
update peerDependencies - webpack

### PR DESCRIPTION
**Pull request by haoxins**
extract-text-webpack-plugin works well with webpack@2

### CODE REVIEW

**Comment by gajus** [comment]
@sokra Is there a technical reason not to merge this?

**Comment by gajus** [comment]
If not, can you add me as a maintainer to GitHub/ NPM, please?

**Comment by AppShipIt** [comment]
Duplicate of #157. @sokra appears MIA.

**Comment by ianks** [comment]
Can we please get this merged @sokra? I cannot shrinkwrap my app because of this.

**Comment by texastoland** [comment]
I reached out on a couple other channels previously too

**Comment by Kovensky** [comment]
There is already a `2.0.0-beta.1` release of this plugin that supports webpack@2.

**Comment by texastoland** [comment]
It still doesn't support the new query API and ignores outstanding bugfixes in #199.

**Comment by sokra** [comment]
done

**Pull request closed without merging**
