### PR TITLE
Remove webpack from peer-dependencies

### PR DESCRIPTION
**Pull request by pgilad**

### CODE REVIEW

**Comment by p0wl** [comment]
:+1:

**Comment by bkniffler** [comment]
+1

**Comment by rmannibucau** [comment]
+1 otherwise a pain to use webpack 2 with older node versions (sometimes required on CI jobs)

**Comment by peter-mouland** [comment]
Is there a reason why this is not desired?

Having upgraded webpack to 2.2.0-rc.4 we are now seeing peer dependency errors which are preventing shrinkwrap.

**Comment by SpaceK33z** [comment]
Closing in favor of #349.

**Pull request closed without merging**
