### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by pgilad**

### CODE REVIEW

**Comment by bkniffler** [comment]
+1

**Comment by deiga** [comment]
Please merge this!

**Comment by bkniffler** [comment]
Yes, I've been watching this pull-request for weeks, and no action has been taken. Please merge!

**Comment by vanesyan** [comment]
@sokra merge this, please!

**Comment by sokra** [comment]
This only updates devDependencies. This shouldn't affect the consumer of this plugin...?

**Comment by SpaceK33z** [comment]
Closing in favor of #349.

**Pull request closed without merging**
