### PR TITLE
Allow webpack 2 RC

### PR DESCRIPTION
**Pull request by SimenB**

### CODE REVIEW

**Comment by abouthiroppy** [comment]
It looks good :)

**Comment by bondz** [comment]
@abouthiroppy yeah?

**Comment by graingert** [comment]
@SimenB can you rebase this?

**Comment by SimenB** [comment]
It was done in https://github.com/webpack/extract-text-webpack-plugin/commit/cbd4690856707cbaaade1e960bfb2aef044cdeb3

**Pull request closed without merging**
